name: Run scheduled job to keep api from sleeping.
on:
  schedule:
    - cron: "*/14 * * * *"
  workflow_dispatch:

jobs:
  run-health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Curl health endpoint
        run: |
          curl -s --location GET "https://home-rentals-api.onrender.com/health"
